# ============================================
# docker-compose.yml
# Microservicios del Sistema de Pagos
# ============================================

networks:
  sistema-Pagos-viaje_camunda-platform:
    external: true  # ⬅️ Busca la red existente

services:

  # ==========================================
  # SERVICIO CLIENTES - Puerto 9080
  # ==========================================
  servicio-clientes:
    build:
      context: ./servicio-clientes
      dockerfile: Dockerfile
    image: Pagos/servicio-clientes:latest
    container_name: servicio-clientes
    hostname: servicio-clientes
    ports:
      - "9080:9080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    networks:
      - sistema-Pagos-viaje_camunda-platform
    restart: unless-stopped

  # ==========================================
  # SERVICIO VUELOS - Puerto 9081
  # ==========================================
  servicio-vuelos:
    build:
      context: ./servicio-vuelos
      dockerfile: Dockerfile
    image: Pagos/servicio-vuelos:latest
    container_name: servicio-vuelos
    hostname: servicio-vuelos
    ports:
      - "9081:9081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    networks:
      - sistema-Pagos-viaje_camunda-platform
    restart: unless-stopped

  # ==========================================
  # SERVICIO HOTELES - Puerto 9082
  # ==========================================
  servicio-hoteles:
    build:
      context: ./servicio-hoteles
      dockerfile: Dockerfile
    image: Pagos/servicio-hoteles:latest
    container_name: servicio-hoteles
    hostname: servicio-hoteles
    ports:
      - "9082:9082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    networks:
      - sistema-Pagos-viaje_camunda-platform
    restart: unless-stopped

  # ==========================================
  # SERVICIO ALQUILER COCHES - Puerto 9083
  # ==========================================
  servicio-alquiler-coches:
    build:
      context: ./servicio-alquiler-coches
      dockerfile: Dockerfile
    image: Pagos/servicio-alquiler-coches:latest
    container_name: servicio-alquiler-coches
    hostname: servicio-alquiler-coches
    ports:
      - "9083:9083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    networks:
      - sistema-Pagos-viaje_camunda-platform
    restart: unless-stopped

  # ==========================================
  # SERVICIO PAGOS - Puerto 9084
  # ==========================================
  servicio-pagos:
    build:
      context: ./servicio-pagos
      dockerfile: Dockerfile
    image: Pagos/servicio-pagos:latest
    container_name: servicio-pagos
    hostname: servicio-pagos
    ports:
      - "9084:9084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    networks:
      - sistema-Pagos-viaje_camunda-platform
    restart: unless-stopped

  # ==========================================
  # SERVICIO Pagos - Puerto 9090 (Orquestador)
  # ==========================================
  servicio-Pagos:
    build:
      context: ./servicio-Pagos
      dockerfile: Dockerfile
    image: Pagos/servicio-Pagos:latest
    container_name: servicio-Pagos
    hostname: servicio-Pagos
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    volumes:
      - ./bpmn:/app/bpmn:ro
    networks:
      - sistema-Pagos-viaje_camunda-platform
    restart: unless-stopped