# ============================================
# docker-compose.yml
# Microservicios del Sistema de Reservas de Viajes
# ============================================
services:

  # ==========================================
  # SERVICIO CLIENTES - Puerto 9080
  # ==========================================
  servicio-clientes:
    build:
      context: ./servicio-clientes
      dockerfile: Dockerfile
    image: reservas/servicio-clientes:latest
    container_name: servicio-clientes
    hostname: servicio-clientes
    ports:
      - "9080:9080"
    environment:
      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_CLIENT_ZEEBE_RESTADDRESS=http://zeebe:8080
    networks:
       - sistema-reservas-viaje_sistema-reserva
    restart: unless-stopped

  # ==========================================
  # SERVICIO VUELOS - Puerto 9081
  # ==========================================
  servicio-vuelos:
    build:
      context: ./servicio-vuelos
      dockerfile: Dockerfile
    image: reservas/servicio-vuelos:latest
    container_name: servicio-vuelos
    hostname: servicio-vuelos
    ports:
      - "9081:9081"
    environment:
      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_CLIENT_ZEEBE_RESTADDRESS=http://zeebe:8080
    networks:
       - sistema-reservas-viaje_sistema-reserva
    restart: unless-stopped

  # ==========================================
  # SERVICIO HOTELES - Puerto 9082
  # ==========================================
  servicio-hoteles:
    build:
      context: ./servicio-hoteles
      dockerfile: Dockerfile
    image: reservas/servicio-hoteles:latest
    container_name: servicio-hoteles
    hostname: servicio-hoteles
    ports:
      - "9082:9082"
    environment:
      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_CLIENT_ZEEBE_RESTADDRESS=http://zeebe:8080
    networks:
       - sistema-reservas-viaje_sistema-reserva
    restart: unless-stopped

  # ==========================================
  # SERVICIO ALQUILER COCHES - Puerto 9083
  # ==========================================
  servicio-alquiler-coches:
    build:
      context: ./servicio-alquiler-coches
      dockerfile: Dockerfile
    image: reservas/servicio-alquiler-coches:latest
    container_name: servicio-alquiler-coches
    hostname: servicio-alquiler-coches
    ports:
      - "9083:9083"
    environment:
      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_CLIENT_ZEEBE_RESTADDRESS=http://zeebe:8080
    networks:
       - sistema-reservas-viaje_sistema-reserva
    restart: unless-stopped

  # ==========================================
  # SERVICIO PAGOS - Puerto 9084
  # ==========================================
  servicio-pagos:
    build:
      context: ./servicio-pagos
      dockerfile: Dockerfile
    image: reservas/servicio-pagos:latest
    container_name: servicio-pagos
    hostname: servicio-pagos
    ports:
      - "9084:9084"
    environment:
      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_CLIENT_ZEEBE_RESTADDRESS=http://zeebe:8080
    networks:
       - sistema-reservas-viaje_sistema-reserva
    restart: unless-stopped

  # ==========================================
  # SERVICIO Pagos - Puerto 9090 (Orquestador)
  # ==========================================
  servicio-reservas:
    build:
      context: ./servicio-reservas
      dockerfile: Dockerfile
    image: reservas/servicio-reservas:latest
    container_name: servicio-reservas
    hostname: servicio-reservas
    ports:
      - "9090:9090"
    environment:
      - CAMUNDA_CLIENT_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_CLIENT_ZEEBE_RESTADDRESS=http://zeebe:8080
    volumes:
      - ./bpmn:/app/bpmn:ro
    networks:
       - sistema-reservas-viaje_sistema-reserva
    restart: unless-stopped


networks:
  sistema-reservas-viaje_camunda-platform:
    external: true  # ⬅️ Busca la red existente