spring:
  application:
    name: servicio-alquiler-coches

  datasource:
    url: jdbc:h2:mem:coches_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9083
  shutdown: graceful

camunda:
  client:
    mode: self-managed
    zeebe:
      gateway-address: zeebe:26500
      rest-address: http://zeebe:8080
    auth:
      username: demo
      password: demo
    deployment:
      enabled: true  # opcional, si quieres desplegar BPMN al iniciar

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    dev.javacadabra: DEBUG
    io.camunda.zeebe: INFO