
# ============================================
# docker-compose-camunda.yml
# Infraestructura de Camunda Platform 8.7
# ============================================
version: '3.8'

services:
  zeebe:
    image: camunda/zeebe:8.7.0
    container_name: camunda-zeebe
    ports:
      - "26500:26500"  # gRPC
      - "9600:9600"    # Metrics
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
    volumes:
      - zeebe_data:/usr/local/zeebe/data
    networks:
      - camunda-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: camunda-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - camunda-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  operate:
    image: camunda/operate:8.7.0
    container_name: camunda-operate
    ports:
      - "8080:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      zeebe:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - camunda-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  tasklist:
    image: camunda/tasklist:8.7.0
    container_name: camunda-tasklist
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      zeebe:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - camunda-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

volumes:
  zeebe_data:
  elasticsearch_data:

networks:
  camunda-network:
    driver: bridge