version: '3.8'

services:
  zeebe:
    image: camunda/zeebe:8.7.0
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      - ZEEBE_BROKER_NETWORK_HOST=0.0.0.0
    volumes:
      - zeebe-data:/usr/local/zeebe/data
    networks:
      - camunda-network
    healthcheck:
      test: ["CMD", "zbctl", "status", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 5

  operate:
    image: camunda/operate:8.7.0
    container_name: operate
    ports:
      - "8080:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=dev
      - CAMUNDA_OPERATE_BACKUP_REPOSITORYNAME=operate
    depends_on:
      zeebe:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - camunda-network

  tasklist:
    image: camunda/tasklist:8.7.0
    container_name: tasklist
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      zeebe:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - camunda-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - camunda-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  zeebe-data:
    driver: local
  elasticsearch-data:
    driver: local

networks:
  camunda-network:
    name: camunda-network
    driver: bridge
