spring:
  application:
    name: servicio-vuelos

  datasource:
    url: jdbc:h2:mem:vuelos_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9081
  shutdown: graceful

camunda:
  client:
    zeebe:
      gateway-address: ${ZEEBE_ADDRESS:localhost:26500}
      rest-address: ${ZEEBE_REST:http://localhost:8080}
      prefer-rest-over-grpc: false
    mode: self-managed
    auth:
      username: demo
      password: demo

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    dev.javacadabra: DEBUG
    io.camunda.zeebe: INFO